baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'RID 3000'

collections:
  announcements:
    output: true
    permalink: /announcements/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: announcements
    values:
      layout: announcements
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
