backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  squash_merges: true

# This line should *not* be indented
# publish_mode: editorial_workflow

media_folder: "/assets/images/announcement_posts/" # Folder where user uploaded files should go
site_url: https://rid3000.org/
display_url: rid3000.org

collections: # A list of collections the CMS should be able to edit
  - name: "announcement" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Announcement" # Used in the UI, ie.: "New Post"
    folder: "_announcements" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}-{{slug}}" # {{year}}-{{month}}-{{day}}-{{slug}}
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Body", name: "body", widget: "markdown"}
